"""
SQLAlchemy ORM models for CyberSentinel.

Three tables:
  scans            – one row per scan job
  check_results    – one row per individual security check within a scan
  recommendations  – one row per remediation recommendation within a scan
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from app.db.database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _new_uuid() -> str:
    return str(uuid.uuid4())


# ── Enums ─────────────────────────────────────────────────────────────────────

class ScanStatus:
    PENDING   = "pending"
    RUNNING   = "running"
    COMPLETED = "completed"
    FAILED    = "failed"

    VALUES = ("pending", "running", "completed", "failed")


class CheckStatus:
    PASS = "pass"
    WARN = "warn"
    FAIL = "fail"
    INFO = "info"

    VALUES = ("pass", "warn", "fail", "info")


class Severity:
    CRITICAL = "critical"
    HIGH     = "high"
    MEDIUM   = "medium"
    LOW      = "low"
    INFO     = "info"

    VALUES = ("critical", "high", "medium", "low", "info")


class Priority:
    CRITICAL = "critical"
    HIGH     = "high"
    MEDIUM   = "medium"
    LOW      = "low"

    VALUES = ("critical", "high", "medium", "low")


# ── Models ────────────────────────────────────────────────────────────────────

class Scan(Base):
    """
    Represents a single scan job.

    lifecycle: pending → running → completed | failed
    """
    __tablename__ = "scans"

    id            = Column(String(36),  primary_key=True, default=_new_uuid)
    url           = Column(String(2048), nullable=False, index=True)
    created_at    = Column(DateTime(timezone=True), nullable=False, default=_utcnow)
    status        = Column(
                        Enum(*ScanStatus.VALUES, name="scan_status"),
                        nullable=False,
                        default=ScanStatus.PENDING,
                    )
    score         = Column(Integer, nullable=True)          # 0–100; null until completed
    scan_duration = Column(Float,   nullable=True)          # seconds; null until completed
    error_message = Column(Text,    nullable=True)          # populated on failed scans only

    # Relationships
    check_results   = relationship("CheckResult",   back_populates="scan", cascade="all, delete-orphan")
    recommendations = relationship("Recommendation", back_populates="scan", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Scan id={self.id!r} url={self.url!r} status={self.status!r}>"


class CheckResult(Base):
    """
    One row per security check performed within a scan.

    check_name examples: "https_available", "ssl_certificate",
                         "hsts_header", "csp_header", "x_frame_options",
                         "cookie_secure", "dns_records"
    """
    __tablename__ = "check_results"

    id         = Column(String(36),  primary_key=True, default=_new_uuid)
    scan_id    = Column(String(36),  ForeignKey("scans.id", ondelete="CASCADE"), nullable=False, index=True)
    check_name = Column(String(64),  nullable=False)
    status     = Column(
                    Enum(*CheckStatus.VALUES, name="check_status"),
                    nullable=False,
                 )
    title      = Column(String(256), nullable=False)
    detail     = Column(Text,        nullable=True)
    severity   = Column(
                    Enum(*Severity.VALUES, name="severity"),
                    nullable=False,
                    default=Severity.INFO,
                 )

    # Relationship
    scan = relationship("Scan", back_populates="check_results")

    def __repr__(self) -> str:
        return f"<CheckResult check={self.check_name!r} status={self.status!r}>"


class Recommendation(Base):
    """
    One row per remediation recommendation tied to a scan.

    Recommendations are generated by the scoring engine for any
    check that results in 'warn' or 'fail'.
    """
    __tablename__ = "recommendations"

    id            = Column(String(36),   primary_key=True, default=_new_uuid)
    scan_id       = Column(String(36),   ForeignKey("scans.id", ondelete="CASCADE"), nullable=False, index=True)
    check_name    = Column(String(64),   nullable=False)
    priority      = Column(
                       Enum(*Priority.VALUES, name="priority"),
                       nullable=False,
                   )
    title         = Column(String(256),  nullable=False)
    description   = Column(Text,         nullable=False)
    reference_url = Column(String(2048), nullable=True)

    # Relationship
    scan = relationship("Scan", back_populates="recommendations")

    def __repr__(self) -> str:
        return f"<Recommendation check={self.check_name!r} priority={self.priority!r}>"
